---
title: "Medicare Analysis"
author: "Pom"
date: "2023-12-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyr)
library(ggplot2)
library(dplyr)
library(stringr)
library(shiny)
library(leaflet)
library(maps)
#library(tidycensus)
#library(plotROC)
library(rpart)
#library(rpart.plot)
#library(randomForest)
#library(FNN)
library(sf)
require(tibble)
require(mosaic)
require(reshape2)
require(leaps)
require(corrplot)
require(car)
library(ggplot2)
library(plotly)
```
```{r}
library(readr)
final_data <- read_csv("Final Medicare Data With SChool Covid.csv")
# divide data into two columns, excluding learningmode 
set_1 <- final_data %>%
  select(3:21)

set_2 <- final_data %>% 
  select(CFR, 22:40)

# best subsets on each, create plot
set1_mod <- regsubsets(CFR ~., data = set_1)
plot(set1_mod, scale = "adjr2") #pop_over_65, black, under18, white, hispanic,native, income_below_poverty, male, unemployment_rate, edu_health_social_industry, health_insur_coverage
```
```{r}

set2_mod <- regsubsets(CFR~., data = set_2)
plot(set2_mod, scale = "adjr2") 
#total_adult_patients_hospitalized_confirmed_covid_7_day_avg, binge, casthma, chd, csmoking, diabetes, sleep,  staffed_adult_icu_bed_occupancy_7_day_avg, Administered_Dose1_Pop_Pct
```

```{r}
# Reduced data
reduced_data <- final_data %>%
  select(CFR, pop_over_65, black, under18, white, hispanic,native, income_below_poverty, male, unemployment_rate, edu_health_social_industry, health_insur_coverage, total_adult_patients_hospitalized_confirmed_covid_7_day_avg, binge, casthma, chd, csmoking, diabetes, sleep,  staffed_adult_icu_bed_occupancy_7_day_avg, Administered_Dose1_Pop_Pct)

# Final best subsets  
reduced_mod <- regsubsets(CFR ~., data = reduced_data)
plot(reduced_mod, scale = "adjr2")
#pop_over_65, black, male, unemployment_rate, under18, health_insur_coverage, chd, csmoking, diabetes, Administered_Dose1_Pop_Pct
```
```{r}
# check for collinearity
set3_corr = cor(select(final_data, pop_over_65, black, male, unemployment_rate, under18, health_insur_coverage, chd, csmoking, diabetes, Administered_Dose1_Pop_Pct))
corrplot.mixed(set3_corr, order = 'AOE') 

data_selected <- final_data %>%
  mutate(log_CFR = log(CFR + 1)) %>%
  select(log_CFR, pop_over_65, black, male, unemployment_rate, under18, health_insur_coverage, chd, csmoking, diabetes, Administered_Dose1_Pop_Pct)

selected_corr = cor(select(data_selected, log_CFR,pop_over_65, black, male, unemployment_rate, under18, health_insur_coverage, chd, csmoking, diabetes, Administered_Dose1_Pop_Pct))
corrplot.mixed(selected_corr, order = 'AOE') 

#Final Model
model <- lm(log(CFR+1) ~ (pop_over_65 + black + male + unemployment_rate + under18 + health_insur_coverage + chd + csmoking + diabetes + Administered_Dose1_Pop_Pct)^2, data = final_data)
summary(model)

#ESS
ess_selected <- final_data %>%
  mutate(log_CFR = log(CFR + 1),
         log_black = log(black + 1)) %>%
  select(log_CFR, pop_over_65, log_black, male, unemployment_rate, under18, health_insur_coverage, chd, csmoking, diabetes, Administered_Dose1_Pop_Pct, MostCommonLearningMode)


ess_model <- lm(log_CFR ~ (pop_over_65 + log_black + male + unemployment_rate + under18 + health_insur_coverage + chd + csmoking + diabetes + Administered_Dose1_Pop_Pct + MostCommonLearningMode)^2, 
                          data = ess_selected)

reduced_model <- lm(log_CFR ~ (pop_over_65 + log_black + male + unemployment_rate + under18 + health_insur_coverage + chd + csmoking + diabetes + Administered_Dose1_Pop_Pct)^2, data = ess_selected)


summary(ess_model) # full model
summary(reduced_model) # reduced model

ess_selected$res <- reduced_model$residuals
ess_selected$fit <- reduced_model$fitted.values

# #Observations: The Adjusted R-squared is higher when MostCommonLearningMode is included in the model (0.5328 vs. 0.5152). This suggests that the inclusion of MostCommonLearningMode provides a slightly better fit of the model to the data, explaining a bit more variance in the dependent variable.
#Some categories of MostCommonLearningMode and their interactions with other variables do show statistical significance, which suggests that MostCommonLearningMode could have a meaningful impact in certain contexts or when interacting with other variables.
#MostCommonLearningMode does seem to have a significant impact on the model to some extent. Its inclusion improves the model fit marginally and some of its categories or interactions with other variables are statistically significant. 


ggplot(aes(x = fit, y = res), data = ess_selected) +
  geom_point() + 
  theme_bw()

# residual vs. explanatory variables
ggplot(aes(x = pop_over_65, y = res), data = ess_selected) +
  geom_point() + 
  theme_bw()

ggplot(aes(x = log_black, y = res), data = ess_selected) +
  geom_point() + 
  theme_bw()

ggplot(aes(x = male, y = res), data = ess_selected) +
  geom_point() + 
  theme_bw()

ggplot(aes(x = unemployment_rate, y = res), data = ess_selected) +
  geom_point() + 
  theme_bw()

ggplot(aes(x = under18, y = res), data = ess_selected) +
  geom_point() + 
  theme_bw()

ggplot(aes(x = health_insur_coverage, y = res), data = ess_selected) +
  geom_point() + 
  theme_bw()

ggplot(aes(x = chd, y = res), data = ess_selected) +
  geom_point() + 
  theme_bw()

ggplot(aes(x = diabetes, y = res), data = ess_selected) +
  geom_point() + 
  theme_bw()

ggplot(aes(x = csmoking, y = res), data = ess_selected) +
  geom_point() + 
  theme_bw()

ggplot(aes(x = Administered_Dose1_Pop_Pct, y = res), data = ess_selected) +
  geom_point() + 
  theme_bw()
# residual normal probability plot
qqnorm(ess_selected$res)
qqline(ess_selected$res)
```

```{r}
#graphing
county_final <- merge(county_spatial, learning, by.x = "GEOID", by.y = "fips")
county_sf <- st_as_sf(county_final, wkt = "geometry")

# Plotting the map with ggplot2
ggplot(data = county_sf) +
  geom_sf(aes(color = MostCommonLearningMode)) +
  theme_minimal() +
  theme(text = element_text(size = 12),  # Set a default font size
        axis.text = element_text(size = 12),  # Set axis text size
        axis.title = element_text(size = 12)) +  # Set axis title size
  labs(title = "Most Common Learning Mode by District",
       fill = "Learning Mode")

# Convert sf object to a dataframe
districts_df <- st_set_geometry(county_sf, NULL)
districts_df <- cbind(districts_df, st_coordinates(st_geometry(county_sf)))# Convert sf object to a dataframe

# Create the plot

colors <- c("In Person" = "blue", "Virtual" = "red", "Hybrid" = "green", "Small Group" = "yellow", "Level 5" = "black", "Level 1" = "white", "Level 3" = "grey", "Closed" = "pink")



# Adjust 'district' and 'state' with the actual column names from your dataset
districts_df$hover_text <- paste("District: ",districts_df$NAME, "\nCity: ", districts_df$CITY, "\nState: ", districts_df$STATE, "\nMost common learning mode: ", districts_df$MostCommonLearningMode)


ui <- fluidPage(
  titlePanel("Interactive Districts Map by Month Index"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("monthIndex",
                  "Month Index:",
                  min = min(districts_df$MonthIndex, na.rm = TRUE),
                  max = max(districts_df$MonthIndex, na.rm = TRUE),
                  value = 1)  # Set to a single value for one-way slider
    ),
    mainPanel(
      plotlyOutput("mapPlot")
    )
  )
)


server <- function(input, output) {
  output$mapPlot <- renderPlotly({
    # Filter data based on slider input
    filtered_data <- districts_df[districts_df$MonthIndex == input$monthIndex, ]
    
    # Plot
    p <- plot_ly(filtered_data, 
                 type = 'scattermapbox', 
                 mode = 'markers',
                 text = ~hover_text,
                 hoverinfo = "text",
                 lon = ~X, 
                 lat = ~Y,
                 marker = list(size = 10,
                               color = ~colors[MostCommonLearningMode],
                               colorscale = 'Viridis')) %>%
      layout(mapbox = list(style = 'open-street-map'))
    
    p
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
write.csv(districts_enriched, "C:\\Users\\Rodolfo G\\Downloads\\district_enriched.csv" )


```